namespace BOF2.Domain;

/// <summary>
/// Nepal's 753 local levels (metropolitan, sub-metropolitan, municipality, rural municipality) by district.
/// Source: github.com/sagautam5/local-states-nepal.
/// </summary>
public static class NepalLocalLevels
{
    public static readonly IReadOnlyDictionary<string, string[]> ByDistrict = new Dictionary<string, string[]>
    {
        ["Achham"] =
        [
            "Bannigadi Jayagad Rural Municipality",
            "Chaurpati Rural Municipality",
            "Dhakari Rural Municipality",
            "Kamalbazar Municipality",
            "Mangalsen Municipality",
            "Mellekh Rural Municipality",
            "Panchadewal Binayak Municipality",
            "Ramaroshan Rural Municipality",
            "Sanfebagar Municipality",
            "Turmakhand Rural Municipality",
        ],
        ["Arghakhanchi"] =
        [
            "Bhumikasthan Municipality",
            "Chhatradev Rural Municipality",
            "Malarani Rural Municipality",
            "Panini Rural Municipality",
            "Sandhikharka Municipality",
            "Sitganga Municipality",
        ],
        ["Baglung"] =
        [
            "Badigad Rural Municipality",
            "Baglung Municipality",
            "Bareng Rural Municipality",
            "Dhorpatan Municipality",
            "Galkot Municipality",
            "Jaimuni Municipality",
            "Khathekhola Rural Municipality",
            "Nishi Khola Rural Municipality",
            "Taman Khola Rural Municipality",
            "Tara Khola Rural Municipality",
        ],
        ["Baitadi"] =
        [
            "Dashrathchanda Municipality",
            "Dilashaini Rural Municipality",
            "Dogdakedar Rural Municipality",
            "Melauli Municipality",
            "Pancheshwar Rural Municipality",
            "Patan Municipality",
            "Purchaudi Municipality",
            "Shivanath Rural Municipality",
            "Sigas Rural Municipality",
            "Surnaya Rural Municipality",
        ],
        ["Bajhang"] =
        [
            "Bitthadchir Rural Municipality",
            "Bungal Municipality",
            "Chhabis Pathibhera Rural Municipality",
            "Durgathali Rural Municipality",
            "Jayaprithvi Municipality",
            "Kedarsyu Rural Municipality",
            "Khaptadchhanna Rural Municipality",
            "Masta Rural Municipality",
            "Saipal Rural Municipality",
            "Surma Rural Municipality",
            "Talkot Rural Municipality",
            "Thalara Rural Municipality",
        ],
        ["Bajura"] =
        [
            "Badimalika Municipality",
            "Budhiganga Municipality",
            "Budhinanda Municipality",
            "Gaumul Rural Municipality",
            "Himali Rural Municipality",
            "Jagannath Rural Municipality",
            "Khaptad Chhededaha Rural Municipality",
            "Swami Kartik Khapar Rural Municipality",
            "Triveni Municipality",
        ],
        ["Banke"] =
        [
            "Baijanath Rural Municipality",
            "Duduwa Rural Municipality",
            "Janaki Rural Municipality",
            "Khajura Rural Municipality",
            "Kohalpur Municipality",
            "Narainapur Rural Municipality",
            "Nepalgunj Sub-Metropolitan City",
            "Rapti-Sonari Rural Municipality",
        ],
        ["Bara"] =
        [
            "Adarsh Kotwal Rural Municipality",
            "Baragadhi Rural Municipality",
            "Bishrampur Rural Municipality",
            "Devtal Rural Municipality",
            "Jitpur Simara Sub-Metropolitan City",
            "Kalaiya Sub-Metropolitan City",
            "Karaiyamai Rural Municipality",
            "Kolhabi Municipality",
            "Mahagadhimai Municipality",
            "Nijgadh Municipality",
            "Pacharauta Municipality",
            "Parwanipur Rural Municipality",
            "Pheta Rural Municipality",
            "Prasauni Rural Municipality",
            "Simaraungadh Municipality",
            "Suwarna Rural Municipality",
        ],
        ["Bardiya"] =
        [
            "Badhaiyatal Rural Municipality",
            "Barbardiya Municipality",
            "Basgadhi Municipality",
            "Geruwa Rural Municipality",
            "Gulariya Municipality",
            "Madhuwan Municipality",
            "Rajapur Municipality",
            "Thakurbaba Municipality",
        ],
        ["Bhaktapur"] =
        [
            "Bhaktapur Municipality",
            "Changunarayan Municipality",
            "Madhyapur Thimi Municipality",
            "Suryabinayak Municipality",
        ],
        ["Bhojpur"] =
        [
            "Aamchok Rural Municipality",
            "Arun Rural Municipality",
            "Bhojpur Municipality",
            "Hatuwagadhi Rural Municipality",
            "Pauwadungma Rural Municipality",
            "Ramprasad Rai Rural Municipality",
            "Salpasilichho Rural Municipality",
            "Shadanand Municipality",
            "Tyamke Maiyum Rural Municipality",
        ],
        ["Chitwan"] =
        [
            "Bharatpur Metropolitan City",
            "Ichchhakamana Rural Municipality",
            "Kalika Municipality",
            "Khairhani Municipality",
            "Madi Municipality",
            "Rapti Municipality",
            "Ratnagar Municipality",
        ],
        ["Dadeldhura"] =
        [
            "Aalitaal Rural Municipality",
            "Ajaymeru Rural Municipality",
            "Amargadhi Municipality",
            "Bhageshwar Rural Municipality",
            "Ganyapadhura Rural Municipality",
            "Navadurga Rural Municipality",
            "Parshuram Municipality",
        ],
        ["Dailekh"] =
        [
            "Aathabis Municipality",
            "Bhagawatimai Rural Municipality",
            "Bhairabi Rural Municipality",
            "Chamunda Bindrasaini Municipality",
            "Dullu Municipality",
            "Dungeshwar Rural Municipality",
            "Gurans Rural Municipality",
            "Mahabu Rural Municipality",
            "Narayan Municipality",
            "Naumule Rural Municipality",
            "Thantikandh Rural Municipality",
        ],
        ["Dang"] =
        [
            "Babai Rural Municipality",
            "Banglachuli Rural Municipality",
            "Dangisharan Rural Municipality",
            "Gadhawa Rural Municipality",
            "Ghorahi Sub-Metropolitan City",
            "Lamahi Municipality",
            "Rajpur Rural Municipality",
            "Rapti Rural Municipality",
            "Shantinagar Rural Municipality",
            "Tulsipur Sub-Metropolitan City",
        ],
        ["Darchula"] =
        [
            "Apihimal Rural Municipality",
            "Duhun Rural Municipality",
            "Lekam Rural Municipality",
            "Mahakali Municipality",
            "Malikarjun Rural Municipality",
            "Marma Rural Municipality",
            "Naugad Rural Municipality",
            "Shailyashikhar Municipality",
            "Vyans Rural Municipality",
        ],
        ["Dhading"] =
        [
            "Benighat Rorang Rural Municipality",
            "Dhunibeshi Municipality",
            "Gajuri Rural Municipality",
            "Galchhi Rural Municipality",
            "Gangajamuna Rural Municipality",
            "Jwalamukhi Rural Municipality",
            "Khaniyabas Rural Municipality",
            "Netrawati Dabjong Rural Municipality",
            "Nilkantha Municipality",
            "Rubi Valley Rural Municipality",
            "Siddhalek Rural Municipality",
            "Thakre Rural Municipality",
            "Tripurasundari Rural Municipality",
        ],
        ["Dhankuta"] =
        [
            "Chaubise Rural Municipality",
            "Chhathar Jorpati Rural Municipality",
            "Dhankuta Municipality",
            "Mahalaxmi Municipality",
            "Pakhribas Municipality",
            "Sahidbhumi Rural Municipality",
            "Sangurigadhi Rural Municipality",
        ],
        ["Dhanusha"] =
        [
            "Aaurahi Rural Municipality",
            "Bateshwar Rural Municipality",
            "Bideha Municipality",
            "Chhireshwarnath Municipality",
            "Dhanauji Rural Municipality",
            "Dhanushadham Municipality",
            "Ganeshman Charnath Municipality",
            "Hansapur Municipality",
            "Janaknandani Rural Municipality",
            "Janakpurdham Sub-Metropolitan City",
            "Kamala Municipality",
            "Lakshminya Rural Municipality",
            "Mithila Municipality",
            "MithilaBihari Municipality",
            "Mukhiyapatti Musharniya Rural Municipality",
            "Nagarain Municipality",
            "Sabaila Municipality",
            "Sahidnagar Municipality",
        ],
        ["Dolakha"] =
        [
            "Baiteshowr Rural Municipality",
            "Bhimeswor Municipality",
            "Bigu Rural Municipality",
            "Gaurishankar Rural Municipality",
            "Jiri Municipality",
            "Kalinchok Rural Municipality",
            "Melung Rural Municipality",
            "Sailung Rural Municipality",
            "Tamakoshi Rural Municipality",
        ],
        ["Dolpa"] =
        [
            "Chharka Tongsong Rural Municipality",
            "Dolpo Buddha Rural Municipality",
            "Jagadulla Rural Municipality",
            "Kaike Rural Municipality",
            "Mudkechula Rural Municipality",
            "She Phoksundo Rural Municipality",
            "Thuli Bheri Municipality",
            "Tripurasundari Municipality",
        ],
        ["Doti"] =
        [
            "Aadarsha Rural Municipality",
            "Badikedar Rural Municipality",
            "Bogatan-Phudsil Rural Municipality",
            "Dipayal Silgadhi Municipality",
            "Jorayal Rural Municipality",
            "K.I.Singh Rural Municipality",
            "Purbichauki Rural Municipality",
            "Sayal Rural Municipality",
            "Shikhar Municipality",
        ],
        ["Eastern Rukum"] =
        [
            "Bhume Rural Municipality",
            "Putha Uttarganga Rural Municipality",
            "Sisne Rural Municipality",
        ],
        ["Gorkha"] =
        [
            "Aarughat Rural Municipality",
            "Ajirkot Rural Municipality",
            "Bhimsen Thapa Rural Municipality",
            "Chumnubri Rural Municipality",
            "Dharche Rural Municipality",
            "Gandaki Rural Municipality",
            "Gorkha Municipality",
            "Palungtar Municipality",
            "Sahid Lakhan Rural Municipality",
            "Siranchowk Rural Municipality",
            "Sulikot Rural Municipality",
        ],
        ["Gulmi"] =
        [
            "Chandrakot Rural Municipality",
            "Chhatrakot Rural Municipality",
            "Dhurkot Rural Municipality",
            "Gulmidarbar Rural Municipality",
            "Isma Rural Municipality",
            "Kaligandaki Rural Municipality",
            "Madane Rural Municipality",
            "Malika Rural Municipality",
            "Musikot Municipality",
            "Resunga Municipality",
            "Rurukshetra Rural Municipality",
            "Satyawati Rural Municipality",
        ],
        ["Humla"] =
        [
            "Adanchuli Rural Municipality",
            "Chankheli Rural Municipality",
            "Kharpunath Rural Municipality",
            "Namkha Rural Municipality",
            "Sarkegad Rural Municipality",
            "Simkot Rural Municipality",
            "Tanjakot Rural Municipality",
        ],
        ["Ilam"] =
        [
            "Chulachuli Rural Municipality",
            "Deumai Municipality",
            "Ilam Municipality",
            "Mai Municipality",
            "Maijogmai Rural Municipality",
            "Mangsebung Rural Municipality",
            "Phakphokthum Rural Municipality",
            "Rong Rural Municipality",
            "Sandakpur Rural Municipality",
            "Suryodaya Municipality",
        ],
        ["Jajarkot"] =
        [
            "Barekot Rural Municipality",
            "Bheri Municipality",
            "Chhedagad Municipality",
            "Junichande Rural Municipality",
            "Kuse Rural Municipality",
            "Nalgad Municipality",
            "Shivalaya Rural Municipality",
        ],
        ["Jhapa"] =
        [
            "Arjundhara Municipality",
            "Barhadashi Rural Municipality",
            "Bhadrapur Municipality",
            "Birtamod Municipality",
            "Buddha Shanti Rural Municipality",
            "Damak Municipality",
            "Gauradaha Municipality",
            "Gaurigunj Rural Municipality",
            "Haldibari Rural Municipality",
            "Jhapa Rural Municipality",
            "Kachankawal Rural Municipality",
            "Kamal Rural Municipality",
            "Kankai Municipality",
            "Mechinagar Municipality",
            "Shivasatakshi Municipality",
        ],
        ["Jumla"] =
        [
            "Chandannath Municipality",
            "Guthichaur Rural Municipality",
            "Hima Rural Municipality",
            "Kanaka Sundari Rural Municipality",
            "Patarasi Rural Municipality",
            "Sinja Rural Municipality",
            "Tatopani Rural Municipality",
            "Tila Rural Municipality",
        ],
        ["Kailali"] =
        [
            "Bardagoriya Rural Municipality",
            "Bhajni Municipality",
            "Chure Rural Municipality",
            "Dhangadhi Sub-Metropolitan City",
            "Gauriganga Municipality",
            "Ghodaghodi Municipality",
            "Godawari Municipality",
            "Janaki Rural Municipality",
            "Joshipur Rural Municipality",
            "Kailari Rural Municipality",
            "Lamkichuha Municipality",
            "Mohanyal Rural Municipality",
            "Tikapur Municipality",
        ],
        ["Kalikot"] =
        [
            "Khandachakra Municipality",
            "Mahawai Rural Municipality",
            "Narharinath Rural Municipality",
            "Pachaljharana Rural Municipality",
            "Palata Rural Municipality",
            "Raskot Municipality",
            "Sanni Triveni Rural Municipality",
            "Shubha Kalika Rural Municipality",
            "Tilagufa Municipality",
        ],
        ["Kanchanpur"] =
        [
            "Bedkot Municipality",
            "Belauri Municipality",
            "Beldandi Rural Municipality",
            "Bhimdatta Municipality",
            "Krishnapur Municipality",
            "Laljhadi Rural Municipality",
            "Mahakali Municipality",
            "Punarbas Municipality",
            "Shuklaphanta Municipality",
        ],
        ["Kapilvastu"] =
        [
            "Banganga Municipality",
            "Bijaynagar Rural Municipality",
            "Buddhabhumi Municipality",
            "Kapilvastu Municipality",
            "Krishnanagar Municipality",
            "Maharajgunj Municipality",
            "Mayadevi Rural Municipality",
            "Shivaraj Municipality",
            "Suddhodan Rural Municipality",
            "Yashodhara Rural Municipality",
        ],
        ["Kaski"] =
        [
            "Annapurna Rural Municipality",
            "Machhapuchchhre Rural Municipality",
            "Madi Rural Municipality",
            "Pokhara Metropolitan City",
            "Rupa Rural Municipality",
        ],
        ["Kathmandu"] =
        [
            "Budhanilkantha Municipality",
            "Chandragiri Municipality",
            "Dakshinkali Municipality",
            "Gokarneshwar Municipality",
            "Kageshwari-Manohara Municipality",
            "Kathmandu Metropolitan City",
            "Kirtipur Municipality",
            "Nagarjun Municipality",
            "Shankharapur Municipality",
            "Tarakeshwar Municipality",
            "Tokha Municipality",
        ],
        ["Kavrepalanchok"] =
        [
            "Banepa Municipality",
            "Bethanchok Rural Municipality",
            "Bhumlu Rural Municipality",
            "Chauri Deurali Rural Municipality",
            "Dhulikhel Municipality",
            "Khani Khola Rural Municipality",
            "Mahabharat Rural Municipality",
            "Mandandeupur Municipality",
            "Namobuddha Municipality",
            "Panauti Municipality",
            "Panchkhal Municipality",
            "Roshi Rural Municipality",
            "Temal Rural Municipality",
        ],
        ["Khotang"] =
        [
            "Aiselukharka Rural Municipality",
            "Barahpokhari Rural Municipality",
            "Diktel Rupakot Majhuwagadhi Municipality",
            "Diprung Chuichumma Rural Municipality",
            "Halesi Tuwachung Municipality",
            "Jantedhunga Rural Municipality",
            "Kepilasgadhi Rural Municipality",
            "Khotehang Rural Municipality",
            "Rawa Besi Rural Municipality",
            "Sakela Rural Municipality",
        ],
        ["Lalitpur"] =
        [
            "Bagmati Rural Municipality",
            "Godawari Municipality",
            "Konjyosom Rural Municipality",
            "Lalitpur Metropolitan City",
            "Mahalaxmi Municipality",
            "Mahankal Rural Municipality",
        ],
        ["Lamjung"] =
        [
            "Besisahar Municipality",
            "Dordi Rural Municipality",
            "Dudhpokhari Rural Municipality",
            "Kwhlosothar Rural Municipality",
            "Madhya Nepal Municipality",
            "Marsyangdi Rural Municipality",
            "Rainas Municipality",
            "Sundarbazar Municipality",
        ],
        ["Mahottari"] =
        [
            "Aaurahi Municipality",
            "Balawa Municipality",
            "Bardibas Municipality",
            "Bhangaha Municipality",
            "Ekdara Rural Municipality",
            "Gaushala Municipality",
            "Jaleshor Municipality",
            "Loharpatti Municipality",
            "Mahottari Rural Municipality",
            "Manara Shiswa Municipality",
            "Matihani Municipality",
            "Pipara Rural Municipality",
            "Ramgopalpur Municipality",
            "Samsi Rural Municipality",
            "Sonama Rural Municipality",
        ],
        ["Makwanpur"] =
        [
            "Bagmati Rural Municipality",
            "Bakaiya Rural Municipality",
            "Bhimphedi Rural Municipality",
            "Hetauda Sub-Metropolitan City",
            "Indrasarowar Rural Municipality",
            "Kailash Rural Municipality",
            "Makawanpurgadhi Rural Municipality",
            "Manahari Rural Municipality",
            "Raksirang Rural Municipality",
            "Thaha Municipality",
        ],
        ["Manang"] =
        [
            "Chame Rural Municipality",
            "Manang Ngisyang Rural Municipality",
            "NarpaBhumi Rural Municipality",
            "Nason Rural Municipality",
        ],
        ["Morang"] =
        [
            "Belbari Municipality",
            "Biratnagar Metropolitan City",
            "Budi Ganga Rural Municipality",
            "Dhanpalthan Rural Municipality",
            "Gramthan Rural Municipality",
            "Jahada Rural Municipality",
            "Kanepokhari Rural Municipality",
            "Katahari Rural Municipality",
            "Kerabari Rural Municipality",
            "Letang Municipality",
            "Miklajung Rural Municipality",
            "Pathari Shanischare Municipality",
            "Rangeli Municipality",
            "Ratuwamai Municipality",
            "Sunawarshi Municipality",
            "Sundar Haraicha Municipality",
            "Urlabari Municipality",
        ],
        ["Mugu"] =
        [
            "Chhayanath Rara Municipality",
            "Khatyad Rural Municipality",
            "Mugum Karmarong Rural Municipality",
            "Soru Rural Municipality",
        ],
        ["Mustang"] =
        [
            "Barhagaun Muktichhetra Rural Municipality",
            "Gharpajhong Rural Municipality",
            "Lo-Ghekar Damodarkunda Rural Municipality",
            "Lomanthang Rural Municipality",
            "Thasang Rural Municipality",
        ],
        ["Myagdi"] =
        [
            "Annapurna Rural Municipality",
            "Beni Municipality",
            "Dhaulagiri Rural Municipality",
            "Malika Rural Municipality",
            "Mangala Rural Municipality",
            "Raghuganga Rural Municipality",
        ],
        ["Nawalpur"] =
        [
            "Baudikali Rural Municipality",
            "Binayi Tribeni Rural Municipality",
            "Bulingtar Rural Municipality",
            "Devachuli Municipality",
            "Gaindakot Municipality",
            "Hupsekot Rural Municipality",
            "Kawasoti Municipality",
            "Madhya Bindu Municipality",
        ],
        ["Nuwakot"] =
        [
            "Belkotgadhi Municipality",
            "Bidur Municipality",
            "Dupcheshwar Rural Municipality",
            "Kakani Rural Municipality",
            "Kispang Rural Municipality",
            "Likhu Rural Municipality",
            "Myagang Rural Municipality",
            "Panchakanya Rural Municipality",
            "Shivapuri Rural Municipality",
            "Suryagadhi Rural Municipality",
            "Tadi Rural Municipality",
            "Tarkeshwar Rural Municipality",
        ],
        ["Okhaldhunga"] =
        [
            "Champadevi Rural Municipality",
            "Chisankhugadhi Rural Municipality",
            "Khiji Demba Rural Municipality",
            "Likhu Rural Municipality",
            "Manebhanjyang Rural Municipality",
            "Molung Rural Municipality",
            "Siddhicharan Municipality",
            "Sunkoshi Rural Municipality",
        ],
        ["Palpa"] =
        [
            "Bagnaskali Rural Municipality",
            "Mathagadhi Rural Municipality",
            "Nisdi Rural Municipality",
            "Purbakhola Rural Municipality",
            "Rainadevi Chhahara Rural Municipality",
            "Rambha Rural Municipality",
            "Rampur Municipality",
            "Ripdikot Rural Municipality",
            "Tansen Municipality",
            "Tinahu Rural Municipality",
        ],
        ["Panchthar"] =
        [
            "Hilihang Rural Municipality",
            "Kummayak Rural Municipality",
            "Miklajung Rural Municipality",
            "Phalelung Rural Municipality",
            "Phalgunanda Rural Municipality",
            "Phidim Municipality",
            "Tumbewa Rural Municipality",
            "Yangwarak Rural Municipality",
        ],
        ["Parasi"] =
        [
            "Bardaghat Municipality",
            "Palhi Nandan Rural Municipality",
            "Pratappur Rural Municipality",
            "Ramgram Municipality",
            "Sarawal Rural Municipality",
            "Sunwal Municipality",
            "Susta Rural Municipality",
        ],
        ["Parbat"] =
        [
            "Bihadi Rural Municipality",
            "Jaljala Rural Municipality",
            "Kushma Municipality",
            "Mahashila Rural Municipality",
            "Modi Rural Municipality",
            "Paiyun Rural Municipality",
            "Phalewas Municipality",
        ],
        ["Parsa"] =
        [
            "Bahudarmai Municipality",
            "Bindabasini Rural Municipality",
            "Birgunj Metropolitan City",
            "Chhipaharmai Rural Municipality",
            "Dhobini Rural Municipality",
            "Jagarnathpur Rural Municipality",
            "Jirabhawani Rural Municipality",
            "Kalikamai Rural Municipality",
            "Pakaha Mainpur Rural Municipality",
            "Parsagadhi Municipality",
            "Paterwa Sugauli Rural Municipality",
            "Pokhariya Municipality",
            "Sakhuwa Prasauni Rural Municipality",
            "Thori Rural Municipality",
        ],
        ["Pyuthan"] =
        [
            "Ayirawati Rural Municipality",
            "Gaumukhi Rural Municipality",
            "Jhimruk Rural Municipality",
            "Mallarani Rural Municipality",
            "Mandavi Rural Municipality",
            "Naubahini Rural Municipality",
            "Pyuthan Municipality",
            "Sarumarani Rural Municipality",
            "Sworgadwari Municipality",
        ],
        ["Ramechhap"] =
        [
            "Doramba Rural Municipality",
            "Gokulganga Rural Municipality",
            "Khandadevi Rural Municipality",
            "LikhuTamakoshi Rural Municipality",
            "Manthali Municipality",
            "Ramechhap Municipality",
            "Sunapati Rural Municipality",
            "Umakunda Rural Municipality",
        ],
        ["Rasuwa"] =
        [
            "Gosaikunda Rural Municipality",
            "Kalika Rural Municipality",
            "Naukunda Rural Municipality",
            "Parbatikunda Rural Municipality",
            "Uttargaya Rural Municipality",
        ],
        ["Rautahat"] =
        [
            "Baudhimai Municipality",
            "Brindaban Municipality",
            "Chandrapur Municipality",
            "Dewahi Gonahi Municipality",
            "Durga Bhagwati Rural Municipality",
            "Gadhimai Municipality",
            "Gaur Municipality",
            "Gujara Municipality",
            "Guruda Municipality",
            "Ishanath Municipality",
            "Katahariya Municipality",
            "Madhav Narayan Municipality",
            "Maulapur Municipality",
            "Paroha Municipality",
            "Phatuwa Bijayapur Municipality",
            "Rajdevi Municipality",
            "Rajpur Municipality",
            "Yamunamai Rural Municipality",
        ],
        ["Rolpa"] =
        [
            "GangaDev Rural Municipality",
            "Lungri Rural Municipality",
            "Madi Rural Municipality",
            "Pariwartan Rural Municipality",
            "Rolpa Municipality",
            "Runtigadi Rural Municipality",
            "Sunchhahari Rural Municipality",
            "Sunil Smiriti Rural Municipality",
            "Thawang Rural Municipality",
            "Triveni Rural Municipality",
        ],
        ["Rupandehi"] =
        [
            "Butwal Sub-Metropolitan City",
            "Devdaha Municipality",
            "Gaidahawa Rural Municipality",
            "Kanchan Rural Municipality",
            "Kotahimai Rural Municipality",
            "Lumbini Sanskritik Municipality",
            "Marchawari Rural Municipality",
            "Mayadevi Rural Municipality",
            "Omsatiya Rural Municipality",
            "Rohini Rural Municipality",
            "Sainamaina Municipality",
            "Sammarimai Rural Municipality",
            "Siddharthanagar Municipality",
            "Siyari Rural Municipality",
            "Suddodhan Rural Municipality",
            "Tilottama Municipality",
        ],
        ["Salyan"] =
        [
            "Bagchaur Municipality",
            "Bangad Kupinde Municipality",
            "Chhatreshwari Rural Municipality",
            "Darma Rural Municipality",
            "Kalimati Rural Municipality",
            "Kapurkot Rural Municipality",
            "Kumakh Rural Municipality",
            "Shaarda Municipality",
            "Siddha Kumakh Rural Municipality",
            "Triveni Rural Municipality",
        ],
        ["Sankhuwasabha"] =
        [
            "BhotKhola Rural Municipality",
            "Chainpur Municipality",
            "Chichila Rural Municipality",
            "Dharmadevi Municipality",
            "Khandbari Municipality",
            "Madi Municipality",
            "Makalu Rural Municipality",
            "Panchkhapan Municipality",
            "Sabhapokhari Rural Municipality",
            "Silichong Rural Municipality",
        ],
        ["Saptari"] =
        [
            "Agnisaira Krishnasavaran Rural Municipality",
            "Balan-Bihul Rural Municipality",
            "Bishnupur Rural Municipality",
            "Bodebarsain Municipality",
            "Chhinnamasta Rural Municipality",
            "Dakneshwori Municipality",
            "Hanumannagar Kankalini Municipality",
            "Kanchanrup Municipality",
            "Khadak Municipality",
            "Mahadeva Rural Municipality",
            "Rajbiraj Municipality",
            "Rajgadh Rural Municipality",
            "Rupani Rural Municipality",
            "Saptakoshi Municipality",
            "Shambhunath Municipality",
            "Surunga Municipality",
            "Tilathi Koiladi Rural Municipality",
            "Tirhut Rural Municipality",
        ],
        ["Sarlahi"] =
        [
            "Bagmati Municipality",
            "Balara Municipality",
            "Barahathwa Municipality",
            "Basbariya Rural Municipality",
            "Bisnu Rural Municipality",
            "Brahampuri Rural Municipality",
            "Chakraghatta Rural Municipality",
            "Chandranagar Rural Municipality",
            "Dhankaul Rural Municipality",
            "Godaita Municipality",
            "Haripur Municipality",
            "Haripurwa Municipality",
            "Hariwan Municipality",
            "Ishowrpur Municipality",
            "Kabilasi Municipality",
            "Kaudena Rural Municipality",
            "Lalbandi Municipality",
            "Malangawa Municipality",
            "Parsa Rural Municipality",
            "Ramnagar Rural Municipality",
        ],
        ["Sindhuli"] =
        [
            "Dudhauli Municipality",
            "Ghyanglekh Rural Municipality",
            "Golanjor Rural Municipality",
            "Hariharpurgadhi Rural Municipality",
            "Kamalamai Municipality",
            "Marin Rural Municipality",
            "Phikkal Rural Municipality",
            "Sunkoshi Rural Municipality",
            "Tinpatan Rural Municipality",
        ],
        ["Sindhupalchok"] =
        [
            "Bahrabise Municipality",
            "Balephi Rural Municipality",
            "Bhotekoshi Rural Municipality",
            "Chautara Sangachowkgadi Municipality",
            "Helambu Rural Municipality",
            "Indrawati Rural Municipality",
            "Jugal Rural Municipality",
            "Lisankhu Rural Municipality",
            "Melamchi Municipality",
            "Panchpokhari Rural Municipality",
            "Sunkoshi Rural Municipality",
            "Tripurasundari Rural Municipality",
        ],
        ["Siraha"] =
        [
            "Arnama Rural Municipality",
            "Aurahi Rural Municipality",
            "Bariyarpatti Rural Municipality",
            "Bhagwanpur Rural Municipality",
            "Bishnupur Rural Municipality",
            "Dhangadhimai Municipality",
            "Golbazar Municipality",
            "Kalyanpur Municipality",
            "Karjanha Municipality",
            "Lahan Municipality",
            "Lakshmipur Patari Rural Municipality",
            "Mirchaiya Municipality",
            "Naraha Rural Municipality",
            "Navarajpur Rural Municipality",
            "SakhuwanankarKatti Rural Municipality",
            "Siraha Municipality",
            "Sukhipur Municipality",
        ],
        ["Solukhumbu"] =
        [
            "Khumbu PasangLhamu Rural Municipality",
            "Likhu Pike Rural Municipality",
            "Maha Kulung Rural Municipality",
            "Mapya Dudhkoshi Rural Municipality",
            "Necha Salyan Rural Municipality",
            "Solu Dudhkunda Municipality",
            "Sotang Rural Municipality",
            "Thulung Dudhkoshi Rural Municipality",
        ],
        ["Sunsari"] =
        [
            "BarahaKshetra Municipality",
            "Barju Rural Municipality",
            "Bhokraha Narsingh Rural Municipality",
            "Dewangunj Rural Municipality",
            "Dharan Sub-Metropolitan City",
            "Duhabi Municipality",
            "Gadhi Rural Municipality",
            "Harinagar Rural Municipality",
            "Inaruwa Municipality",
            "Itahari Sub-Metropolitan City",
            "Koshi Rural Municipality",
            "Ramdhuni Municipality",
        ],
        ["Surkhet"] =
        [
            "Barahatal Rural Municipality",
            "Bheriganga Municipality",
            "Birendranagar Municipality",
            "Chaukune Rural Municipality",
            "Chingad Rural Municipality",
            "Gurbhakot Municipality",
            "Lekbeshi Municipality",
            "Panchapuri Municipality",
            "Simta Rural Municipality",
        ],
        ["Syangja"] =
        [
            "Aandhikhola Rural Municipality",
            "Arjun Chaupari Rural Municipality",
            "Bheerkot Municipality",
            "Biruwa Rural Municipality",
            "Chapakot Municipality",
            "Galyang Municipality",
            "Harinas Rural Municipality",
            "Kaligandaki Rural Municipality",
            "Phedikhola Rural Municipality",
            "Putalibazar Municipality",
            "Waling Municipality",
        ],
        ["Tanahun"] =
        [
            "AnbuKhaireni Rural Municipality",
            "Bandipur Rural Municipality",
            "Bhanu Municipality",
            "Bhimad Municipality",
            "Byas Municipality",
            "Devghat Rural Municipality",
            "Ghiring Rural Municipality",
            "Myagde Rural Municipality",
            "Rishing Rural Municipality",
            "Suklagandaki Municipality",
        ],
        ["Taplejung"] =
        [
            "Aathrai Triveni Rural Municipality",
            "Maiwa Khola Rural Municipality",
            "Meringden Rural Municipality",
            "Mikwa Khola Rural Municipality",
            "Pathibhara Yangwarak Rural Municipality",
            "Phaktanglung Rural Municipality",
            "Phungling Municipality",
            "Sidingwa Rural Municipality",
            "Sirijangha Rural Municipality",
        ],
        ["Terhathum"] =
        [
            "Aathrai Rural Municipality",
            "Chhathar Rural Municipality",
            "Laligurans Municipality",
            "Menchayayem Rural Municipality",
            "Myanglung Municipality",
            "Phedap Rural Municipality",
        ],
        ["Udayapur"] =
        [
            "Belaka Municipality",
            "Chaudandigadhi Municipality",
            "Katari Municipality",
            "Limchungbung Rural Municipality",
            "Rautamai Rural Municipality",
            "Tapli Rural Municipality",
            "Triyuga Municipality",
            "Udayapurgadhi Rural Municipality",
        ],
        ["Western Rukum"] =
        [
            "Aathabiskot Municipality",
            "Banphikot Rural Municipality",
            "Chaurjahari Municipality",
            "Musikot Municipality",
            "SaniBheri Rural Municipality",
            "Triveni Rural Municipality",
        ],
    };

    public static bool IsValid(string? district, string? localLevel) =>
        district is not null && localLevel is not null &&
        ByDistrict.TryGetValue(district, out var levels) && levels.Contains(localLevel);
}
